server:
  port: 8091
resilience4j:
  circuitbreaker:
    instances:
      orderService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 5
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 2
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

spring:
  profiles:
    active: @environment@

transacciones:
  uri: @transacciones@

bancos:
  uri: @bancos@

proveedores:
  uri: @proveedores@